### PR TITLE
Update gif.ski to 1.6.1

### LINKED ISSUE #85: Switch from GCC to Clang
Currently we use GCC to be able to use OpenMP, but it seems like it's actually possible to use OpenMP with the built-in Clang version in Xcode in combination with `brew install libomp`.

Resources:
- https://stackoverflow.com/a/55726616/64949
- https://stackoverflow.com/questions/44380459/is-openmp-available-in-high-sierra-llvm
- https://github.com/microsoft/LightGBM/pull/1501/files

I think it would be nicer to be able to use the built-in compiler as it means less chance of issues and probably better performance.

@kornelski Thoughts?

### LINKED ISSUE #261: Artifacts on 0-20% quality with screen recording
Screen Recording 2022-01-05 at 20 04 53

Source video: https://user-images.githubusercontent.com/170270/148274565-5ec81390-60fc-4eab-ad18-b2839deca842.mov

@kornelski Is there anything the gifski library can do about this?

### PR DESCRIPTION
**Pull request by kornelski**
GCC no longer required. Now multi-threading is built-in. Also uses new fancy almost-native Xcode project file instead of a Makefile.

Fixes #85 
Fixes #261

### CODE REVIEW

**Comment by sindresorhus** [comment]
It seems like this fixes #261. Did you do anything to specifically fix it?
148274565-5ec81390-60fc-4eab-ad18-b2839deca842

**Comment by sindresorhus** [comment]
Performance seems to be the same or slightly better 👍

**Comment by sindresorhus** [comment]
Can you update https://github.com/sindresorhus/Gifski/blob/f8f3c8a3f39845c01349383c3abadb934cd58939/readme.md?plain=1#L76 with how to build the gif.ski static library now?

**Comment by sindresorhus** [comment]
I'm getting a warning when building:

> ld: warning: object file (/Users/sindresorhus/Library/Developer/Xcode/DerivedData/Gifski-covufrfbnkqrunfagfxjgrfngrhp/Build/Products/Release/libgifski_static.a(gifski.gifski.dac060e5-cgu.15.rcgu.o)) was built for newer macOS version (12.1) than being linked (11.0)

I think you need to set the macOS target in the gifski-api project to macOS 10.15 (same as Gifski).

**Comment by kornelski** [comment]
New gifski uses the latest imagequant, which has improved selection of colors for low-color images.

**Comment by sindresorhus** [comment]
@kornelski When archiving Gifski, I now get an error from the new build stuff:

> Multiple commands produce '/Users/sindresorhus/Library/Developer/Xcode/DerivedData/Gifski-covufrfbnkqrunfagfxjgrfngrhp/Build/Intermediates.noindex/ArchiveIntermediates/Gifski/BuildProductsPath/Release/libgifski_static.a':
> 1) That command depends on command in Target 'gifski-staticlib' (project 'gifski'): script phase “Universal Binary lipo”
> 2) Target 'gifski-staticlib' (project 'gifski') has symlink command from '/Users/sindresorhus/Library/Developer/Xcode/DerivedData/Gifski-covufrfbnkqrunfagfxjgrfngrhp/Build/Intermediates.noindex/ArchiveIntermediates/Gifski/BuildProductsPath/Release/libgifski_static.a' to '/Users/sindresorhus/Library/Developer/Xcode/DerivedData/Gifski-covufrfbnkqrunfagfxjgrfngrhp/Build/Intermediates.noindex/ArchiveIntermediates/Gifski/IntermediateBuildFilesPath/UninstalledProducts/macosx/libgifski_static.a'

**Comment by kornelski** [comment]
Eh, Xcode…

I think I've fixed it. https://github.com/sindresorhus/Gifski/pull/264 It turns out that `BUILT_PRODUCTS_DIR` is supposed to be the dir where you put products you've built.

**Pull request merged**
