### PR TITLE
Workaround macOS 11 issue with decoding some videos

### PR DESCRIPTION
**Pull request by sindresorhus**
#202

Here's a build for this PR: [Gifski.app.zip](https://github.com/sindresorhus/Gifski/files/5352168/Gifski.app.zip)

### CODE REVIEW

**Comment by sindresorhus** [comment]
@Oleg-Chashko Can you give the build a try?

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko Can you give the build a try?

@sindresorhus 
Thank you, I'll try this build. If I find errors I will write to you.

**Comment by Oleg-Chashko** [comment]
@sindresorhus 
Checked in different modes, with different video files, crashes and no errors found. Thanks.

**Comment by sindresorhus** [comment]
That's weird. It works fine for me. Are you on macOS 11 beta 9? It crashes during the conversion, right?

Could you open the Console app, go to "Crash Reports" and share the report for Gifski?

**Comment by Oleg-Chashko** [comment]
> That's weird. It works fine for me. Are you on macOS 11 beta 9? It crashes during the conversion, right?
> 
> Could you open the Console app, go to "Crash Reports" and share the report for Gifski?

You did not understand me. Works great!

**Comment by kornelski** [comment]
This does NOT fix the issue for me. In my case a decoding error also happens at 33% of the video.


[bla 20.45.37.mov.zip](https://github.com/sindresorhus/Gifski/files/5354782/bla.20.45.37.mov.zip)

**Comment by Oleg-Chashko** [comment]
Test file: bla 20.45.37.mov.zip
**Console log:**
Sandbox: Gifski(3771) deny(1) sysctl-write kern.system_version_compat
Violation:       deny(1) sysctl-write kern.system_version_compat
Process:         Gifski [3771]
Path:            /Applications/Gifski.app/Contents/MacOS/Gifski
Load Address:    0x107026000
Identifier:      com.sindresorhus.Gifski
Version:         39 (2.9.0)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /Applications/Gifski.app/Contents/MacOS/Gifski
User ID:         501

Date/Time:       2020-10-09 14:37:53.924 GMT+2
OS Version:      macOS 11.0 (20A5384c)
Report Version:  8

MetaData: {"profile-in-collection":false,"process-path":"\/Applications\/Gifski.app\/Contents\/MacOS\/Gifski","primary-filter":"sysctl-name","operation":"sysctl-write","responsible-process-user-uuid":"DF1FAB44-B566-41D4-A33D-969CFA0957D4","apple-internal":false,"flags":5,"normalized_target":["kern.system_version_compat"],"platform_binary":"no","errno":1,"container":"\/Users\/elena_chashko\/Library\/Containers\/com.sindresorhus.Gifski\/Data","summary":"deny(1) sysctl-write kern.system_version_compat","signing-id":"com.sindresorhus.Gifski","team-id":"YG56YK5RN5","responsible-process-uid":501,"profile-flags":0,"responsible-process-path":"\/Applications\/Gifski.app\/Contents\/MacOS\/Gifski","pid":3771,"process":"Gifski","build":"macOS 11.0 (20A5384c)","action":"deny","target":"kern.system_version_compat","platform-policy":false,"hardware":"Mac","primary-filter-value":"kern.system_version_compat","sysctl-name":"kern.system_version_compat","uid":501,"platform-binary":false}

Thread 0 (id: 173207):
0   libsystem_kernel.dylib        	0x00007fff2036b3ae __sysctlbyname + 10
1   libSystem.B.dylib             	0x00007fff2a5f073c libSystem_initializer + 441
2   dyld                          	0x0000000116224079 ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 559
3   dyld                          	0x0000000116224478 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
4   dyld                          	0x000000011621ed1a ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 492
5   dyld                          	0x000000011621ec85 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 343
6   dyld                          	0x000000011621ec85 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 343
7   dyld                          	0x000000011621cb82 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 188
8   dyld                          	0x000000011621cc22 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 82
9   dyld                          	0x000000011620962f dyld::initializeMainExecutable() + 199
10  dyld                          	0x000000011620f9a4 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 8288
11  dyld                          	0x000000011620822b dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 457
12  dyld                          	0x0000000116208025 _dyld_start + 37
13  Gifski                        	0x0000000000000001

Thread 1 (id: 173235):
0   libsystem_pthread.dylib       	0x00007fff2039a4a4 start_wqthread + 0

Thread 2 (id: 173236):

Binary Images:
       0x107026000 -        0x107225fff  com.sindresorhus.Gifski (2.9.0 - 39) <5fc4e54a-449c-3203-ad0d-0de998de79ca> /Applications/Gifski.app/Contents/MacOS/Gifski
       0x116207000 -        0x11629f98f  dyld (832.5) <eb78b26d-29b3-3ba9-ac68-968c2ae40198> /usr/lib/dyld
    0x7fff20369000 -     0x7fff20397fff  libsystem_kernel.dylib (7195.40.89.100.3) <696dc83e-6827-3c18-95a1-192c2948b802> /usr/lib/system/libsystem_kernel.dylib
    0x7fff20398000 -     0x7fff203a3ff7  libsystem_pthread.dylib (454.40.1) <0e26cc7c-3836-348f-8198-dc8c1f84e55a> /usr/lib/system/libsystem_pthread.dylib
    0x7fff2a5ef000 -     0x7fff2a5f0ff3  libSystem.B.dylib (1292) <d8a8b86a-6510-3ae7-b5c2-1bf36b6e2538> /usr/lib/libSystem.B.dylib

AddInstanceForFactory: No factory registered for id <CFUUID 0x600000fd3140> F8BB1C28-BAE8-11D6-9C31-00039315CD46

identifier=com.sindresorhus.Gifski, pid=3771, auid=501, euid=501, binary_path=/Applications/Gifski.app/Contents/MacOS/Gifski attempted to call TCCAccessRequest for kTCCServiceAccessibility without the recommended com.apple.private.tcc.manager.check-by-audit-token entitlement

**Comment by sindresorhus** [comment]
@kornelski Ugh. That makes it more complicated. What is your recommendation? Should we just silently ignore decode errors? Or maybe ignore them, but present them at the end as a summary? The question is, do we actually lose frames from the decode errors.

**Comment by kornelski** [comment]
Maybe ignore errors if they're less than x% of frames that succeeded?

**Comment by sindresorhus** [comment]
@kornelski In your recording, about 11% of the frames failed to decode, so I went with 20%, just to be safe.

**Review by kornelski — APPROVED** [review]

**Pull request merged**
