### PR TITLE
Properly fix GIF looping when the quality is less than 100%

### LINKED ISSUE #159: Looping is not working when using lower quality (gifsicle)
Try the latest App Store version with a GIF. Make sure the quality is at 100%. Then drag the thumbnail into Chrome and see that it loops. Try again, but lower the quality (gifsicle kicks in) and notice how looping doesn't work in Chrome (or Safari).

This was introduced in https://github.com/sindresorhus/Gifski/commit/50b24f2e058aca147a2ff3bc0a7d10e582f23765. Seems that the gifsicle part of the code doesn't correctly handle the `once` setting.

I've submitted a temporary fix to Apple as it's kinda critical: https://github.com/sindresorhus/Gifski/commit/09752faa308f72008da7c3985bd323accb9f5525

// @kornelski

### PR DESCRIPTION
**Pull request by kornelski**
Fixes #159

### CODE REVIEW

**Comment by sunshinejr** [comment]
that was fast @kornelski 🚀 Do we need to also revert the [flag commit](https://github.com/sindresorhus/Gifski/commit/09752faa308f72008da7c3985bd323accb9f5525)?

**Comment by kornelski** [comment]
Yup

**Comment by sindresorhus** [comment]
I have checked out this PR locally, reverted https://github.com/sindresorhus/Gifski/commit/09752faa308f72008da7c3985bd323accb9f5525, and then cleaned and rebuilt all the targets, but it still doesn't loop the GIF for me in Chrome.

**Comment by kornelski** [comment]
Hmm…

**Comment by kornelski** [comment]
I can't reproduce. It loops fine for me.

**Comment by sindresorhus** [comment]
I tried again now, and I still cannot make it loop. This is the video I've been trying it with: [Unicorn.mp4.zip](https://github.com/sindresorhus/Gifski/files/3830844/Unicorn.mp4.zip)

---

> I can't reproduce. It loops fine for me.

Did you clean and rebuild all the targets? (`Carthage`,`libgifski`, `gifski`)

**Comment by sindresorhus** [comment]
@sunshinejr Would you be able to try this and check if it works for you?

**Comment by kornelski** [comment]
Got it now. loopity-loopy

**Comment by sindresorhus** [comment]
Yay! Thanks for fixing this 👌

**Pull request merged**
