### PR TITLE
Improve file size estimate

### LINKED ISSUE #41: Improve file size estimate
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/gifski-app/issues/41)

GifSki is my go-to gif-app. But,,,,

### Problem 😤
I always have to convert videos 3 times  before I get close to the size I want. Changing FPS, Quality and resolution to hit the sweet spot. Which in my case is usually under 5mb.

### Why is this relevant? 💡
I create a lot of gif videos to show how apps work etc. I host these on github, because GitHub is where work happens 👔. I need to be able to post these videos in GitHub comment fields etc. Github has a max limit of around 5.2mb So I want to keep my gif videos a bit under 5mb.

### Thinking 🤔
So Gifski is unique because it creates a unique Color-maps for each frame. Ball-park correct? So the file guesstimater of old doesn't work, you used to be able to do 256 * FramesInTotal = size. But you can't now because each frame is not defined from scratch.

### Solution 💰
✨ `FileSizeGuestimatorPro.swift` ✨ 😇

1. On a background thread (at startup, and while user interacts with settings)
2. `let segmentCount = (TotalFrameCount 240/4) = 60`
3. `let sizes:Int = (0..<4).indecies.map {i in GifSkiConverter.gifFrame(video:test.mp4,frameIdx:i* segmentCount).size }`
4. `let size:Int = sizes.reduce(0,+) * segmentCount `
5. `onBGComplete = {/*double the sampling, on each pass*/} //👈 rinse repeat until the size is hardned, or user changes variables or cancels`
6. Bonus point if these samples are re-used in the final conversion. 

---

**Note:** This is not an easy issue and requires good Swift and macOS/iOS experience.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $182.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($180.00)
- [0maxxam0 0maxxam0](https://issuehunt.io/u/0maxxam0) ($2.00)
### Submitted pull Requests
- [#129 Improved Estimate](https://issuehunt.io/r/sindresorhus/gifski-app/pull/129)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by sindresorhus**
I tried out many different algorithms and variants, and in the end, found that this one produced the most accurate estimate:
- Get all the normal frame time codes.
- Pick 5 consecutive samples from 5 evenly distributed places in the video.
- Convert with current settings.
- Divide by the original frame count compared to the one used in the estimate.

Fixes #41 

---

Here is a build: [Gifski - with estimate.zip](https://github.com/sindresorhus/Gifski/files/5388439/Gifski.-.with.estimate.zip)

**Please try it out on various videos and check the estimate compared to the final result. The most important part is that the estimate never shows less than the actual file.**

Note: The code and look are not done. It should be cleaned up a lot, but I would like to finalize the algorithm first.

Some potential optimization would be to run the 5 samples concurrently, but I don't plan to do that in this PR. I'll add a TODO comment.

---

Open questions:

- [x] Should we still show the naive estimate (the one we currently use) while the good estimate is being generated? Currently, the estimate takes from 5 - 15 seconds. The downside of showing the naive one is that it can be woefully incorrect sometimes.

### CODE REVIEW

**Comment by kornelski** [comment]
Looks good.

I see you're adding 10% just in case. I have an idea to make it more scientific: measure frame sizes in bytes, and compute standard deviation of frame sizes. If the deviation is large, then the estimate is uncertain and should be inflated. If all frame sizes are about the same, then the estimate is likely to be accurate.

**Comment by kornelski** [comment]
Alternative solution, which I think we've discussed previously, is to start the actual final conversion in the background, and use it for the estimate. When user presses start, instead of restarting, just reuse the in-progress conversion. This will have disadvantage of using frames from the beginning for the estimate, but OTOH it will make conversion seem faster, since it will get a head start.

**Comment by sindresorhus** [comment]
> I have an idea to make it more scientific: measure frame sizes in bytes, and compute standard deviation of frame sizes. If the deviation is large, then the estimate is uncertain and should be inflated. If all frame sizes are about the same, then the estimate is likely to be accurate.

That's a good idea. I'll try it out.

> This will have disadvantage of using frames from the beginning for the estimate

I tried that too and the estimate was much worse. We really evenly spread out samples to get an accurate estimate. I rather have a more accurate estimate over a slightly shorter conversion time.

**Comment by sunshinejr** [comment]
@sindresorhus this is looking really good! tried few recordings from apps (this is mostly my use case for Gifski), and the file size was always a bit bigger, but not that much. E.g. I saw naive 59mb, then updated to 35,1 and then it generated 34,9. This is a really big improvement for me. And personally, I'd skip the "naive" and maybe add a loader or a "Estimating filesize" text?

**Comment by kornelski** [comment]
Regarding naive estimate:

* Show a min-max range. "20MB-50MB" makes it clearer how imprecise it is.

* Once you get any better estimate, remember the ratio between the naive and the better estimates. Apply that ratio to later naive estimates. This will give you decent estimates real time for changing parameters.

**Comment by sindresorhus** [comment]
> Show a min-max range. "20MB-50MB" makes it clearer how imprecise it is.

How should we get the range? Just expand the current naive estimate both ways to get a lower/upper bound, or do you have something more clever in mind?

> Once you get any better estimate, remember the ratio between the naive and the better estimate. Apply that ratio to later naive estimates. This will give you decent estimates real time for changing parameters.

That's a good idea.

**Comment by kornelski** [comment]
For lower/upper guesstimate I had in mind plugging in different constants/assumptions into the algorithm.

**Comment by sindresorhus** [comment]
> For lower/upper guesstimate I had in mind plugging in different constants/assumptions into the algorithm.

Let's continue this in https://github.com/sindresorhus/Gifski/issues/130.

**Comment by sindresorhus** [comment]
I don't have time to implement and test all these things right now, but I've opened an issue to track them: https://github.com/sindresorhus/Gifski/issues/211

**Comment by sindresorhus** [comment]
I think it's more important to get this out there now. A lot of people have complained about inaccurate estimates.

**Pull request merged**
