### PR TITLE
Present the open panel when clicking initial view

### PR DESCRIPTION
**Pull request by yonihemi**
Hits me Every. Single. Time.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Should we indicate to the user that they can just click?

"Drop a Video" => "Drop a Video or Click Here" (Not really happy about it being more verbose though. Maybe it's not worth it)

**Comment by sindresorhus** [comment]
This doesn't work, if I drag and drop a video, then click "Cancel", and then try to click "Drop a Video".

**Comment by yonihemi** [comment]
@sindresorhus Fixed.

> Should we indicate to the user that they can just click?

IMO not worth it as will become too long. Silly people like me don't read anyway (hence the clicking).

**Comment by sindresorhus** [comment]
I noticed an annoying issue with this now. It now presents the open panel when you drag the window around. I think it should only activate on an explicit click, not dragging. (Note that the user can click and drag anywhere in the window to drag the window).

**Comment by sindresorhus** [comment]
@yonihemi Would you be able to fix the above? If not, I'll have to revert this PR.

**Comment by sindresorhus** [comment]
Reverted

**Pull request merged**
