### PR TITLE
Use custom presentation animator

### LINKED ISSUE #108: Use `NSViewController.present()` with custom animator
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/gifski-app/issues/108)

Currently, we do this: https://github.com/sindresorhus/Gifski/blob/56511ac4c7deb68b2e39490e0bef45180634b128/Gifski/util.swift#L2436-L2455

The benefit of using `present` is that it's possible to dismiss the view controller to go back to the previous one. For example, when the user cancels the editing, we could just dismiss that view controller.

https://developer.apple.com/documentation/appkit/nsviewcontroller/1434431-present
https://stackoverflow.com/questions/28454291/transitioning-between-view-controller-os-x/28493373#28493373

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Submitted pull Requests
- [#139 Use custom presentation animator](https://issuehunt.io/r/sindresorhus/gifski-app/pull/139)
- [#241 Use NSViewController.present() with custom animator #108](https://issuehunt.io/r/sindresorhus/gifski-app/pull/241)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by SergeyKuryanov**
This PR is attempt to Fixes #108 

Custom animator was added and used.

Unfortunately app crashes when you try to `dismiss` controller presented with `present(_, animator:). I assume this is because `window.contentViewController` being replaced.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#108: Use `NSViewController.present()` with custom animator](https://issuehunt.io/repos/119822304/issues/108)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by sindresorhus** [comment]
> The benefit of using present is that it's possible to dismiss the view controller to go back to the previous one. For example, when the user cancels the editing, we could just dismiss that view controller.

The point of #108 is to not replace, but to push into the view controller stack.

**Comment by SergeyKuryanov** [comment]
@sindresorhus may you please clarify what you mean by `push into the view controller stack`? I have little experience with MacOs dev, but as far as I know there is no controllers stack (like on iOS). We can try layer views on top to simulate this, or you mean something different?

**Comment by sindresorhus** [comment]
While I haven't done this before, I think it's possible. Instead of replacing `window.contentViewController` each time, we give that view controller the responsibility of presenting and dismissing other view controllers.

https://developer.apple.com/documentation/appkit/nsviewcontroller/1434497-presentedviewcontrollers
https://developer.apple.com/documentation/appkit/nsviewcontroller/1434447-dismiss

**Comment by SergeyKuryanov** [comment]
FYI: PR is not abandoned, just looking for solution.

**Comment by sindresorhus** [comment]
Friendly bump :)

**Comment by sindresorhus** [comment]
Closing as this is not moving forward. Open a new PR if you ever get to this ;)

**Pull request closed without merging**
