### PR TITLE
Add checkbox to disable GIF looping

### PR DESCRIPTION
**Pull request by yonihemi**
Resolves https://github.com/sindresorhus/Gifski/issues/137.
Incorporated suggestions from https://github.com/sindresorhus/Gifski/pull/147.

### CODE REVIEW

**Comment by sindresorhus** [comment]
How it looks like now:

Screenshot 2019-10-24 at 10 55 52

**Comment by sunshinejr** [comment]
Hmm I think the "Loop" may be a little bit too vague. "Loop forever" or "Loop GIF" or even "Infinite loop" are all fine with me.

**Comment by sindresorhus** [comment]
Let's go with `Loop Forever` then.

**Comment by yonihemi** [comment]
Screen Shot 2019-10-25 at 12 11 49

**Comment by sindresorhus** [comment]
Thanks for your high-quality work on this, @yonihemi 🙌

**Pull request merged**
