### PR TITLE
Loop the playback when “Loop Forever” is enabled

### PR DESCRIPTION
**Pull request by sindresorhus**
I tried using [`AVPlayerLooper`](https://developer.apple.com/documentation/avfoundation/avplayerlooper) first, but that removes the editing controls when looping. The looping seems smooth using the current method anyway.

### CODE REVIEW

**Comment by kornelski** [comment]
Have you tested with airplay? Hopefully without audio macOS won't give it the lag, but videos with audio have a 2-second delay on seek.

**Comment by sindresorhus** [comment]
Just tested now. When it plays to the end, it pauses for 2 seconds to make the audio catch up, before beginning from the start again. I also tested with `AVPlayerLooper` and same result.

Do we even want audio when playing there at all? I don't really see the point personally. So one fix could be to just remove all audio tracks before presenting the editor.

**Comment by sindresorhus** [comment]
I tried https://developer.apple.com/documentation/avfoundation/avplayer/1387441-allowsexternalplayback, but it seems to have no impact on audio.

**Comment by kornelski** [comment]
Removing audio from preview would make a lot of sense. I'm not familiar with the APIs to advise how.

**Comment by sindresorhus** [comment]
I did find a way to force the audio to play just in the editor. Using https://developer.apple.com/documentation/avfoundation/avplayer/1390717-audiooutputdeviceuniqueid. But it's a nightmare to find the built-in output device ID (thousands of lines of low-level code).

Let's go with removing the audio.

**Comment by sindresorhus** [comment]
Audio removed.

**Comment by sindresorhus** [comment]
I'm gonna manually test this a bit more before merging. I want to ensure there are no regressions.

**Pull request merged**
