### PR TITLE
Improve navigation

### LINKED ISSUE #112: Improve navigation
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/gifski-app/issues/112)

Currently when you cancel the conversion it goes back to the “drop video” controller. We should change that so it goes back to the “edit video” controller.

Additionally we should add back button to the “result” controller, it should also go back to the “edit video” controller.

See #111 for more context.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#133 Feature/improve navigation](https://issuehunt.io/r/sindresorhus/gifski-app/pull/133)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by Ybrin**
Fixes #112 

I am saving and passing a kind of "state" to the controllers so they can switch back to the Edit controller with this state.

Cancel jumps back to the Edit controller and there is a "Start Over" Button now in the ConversionCompletedViewController.

I already merged #131 into this PR as there was changed a lot and I don't want to have all those merge conflicts later. Please merge #131 first or let me know to revert those changes so this PR can be merged at least...

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#112: Improve navigation](https://issuehunt.io/repos/119822304/issues/112)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by sindresorhus** [comment]
Alternatively, we could go for a back button like the App Store app:

Screenshot 2019-09-13 at 14 12 33

Thought, I think I still prefer the iOS style, as we already have filled buttons.

Opinions?

**Comment by Ybrin** [comment]
@sindresorhus 

I can do #108 first. Actually this was my first thought too but I didn't see the issue for it and assumed you want to use your custom push...

I guess the App Store Button would be easier but I don't really have a preference. We don't have any other Navigation Buttons yet so it doesn't really matter I guess...

**Comment by sindresorhus** [comment]
I made some quick mockups:

Screenshot-2019-09-20-at-12 53 30-2
Screenshot-2019-09-20-at-12 53 30

I still prefer the iOS style. @sunshinejr Opinions?

**Comment by sunshinejr** [comment]
I like both, with a slight advantage to the the first one (arrow button) as I love how all of the buttons share the same style 😄

**Comment by sindresorhus** [comment]
Lets go with the first one as it’s more Mac-like. I think you can use https://developer.apple.com/documentation/appkit/nsimagenamegobacktemplate

**Pull request closed without merging**
