### PR TITLE
Upgrade libgifski to 1.4.4

### LINKED ISSUE #231: Produces empty GIF for very short video
@kornelski https://github.com/sindresorhus/Gifski/pull/222 introduced an issue where this video produces an empty invalid file: [Short.mp4.zip](https://github.com/sindresorhus/Gifski/files/5950638/Short.mp4.zip)

Before this change:

Short

After:

[Short.gif.zip](https://github.com/sindresorhus/Gifski/files/5950674/Short.gif.zip)

---

I realize the video is way too short and weird, but we should never produce an invalid GIF. According to logging, it successfully generated 2 frames and passed them to libgifski.

### PR DESCRIPTION
**Pull request by sindresorhus**
And also switch to RGBA.

Build: [Gifski.app.zip](https://github.com/sindresorhus/Gifski/files/6630380/Gifski.app.zip)

---

Fixes #231

### CODE REVIEW

**Comment by sindresorhus** [comment]
@kornelski Would you be able to test on a M1 Mac?

**Comment by kornelski** [comment]
I can't test. My M1 Mac is still bricked by Apple's servers refusing to authorize a reinstall of the OS.

**Comment by sindresorhus** [comment]
@leejongyoung @haakonstorm Would either of you be able to quickly test that this build still works fine on an Apple Silicon Mac?

**Comment by haakonstorm** [comment]
Testing!

**Comment by haakonstorm** [comment]
Screen Recording 2021-06-12 at 13 20 13

**Comment by haakonstorm** [comment]
Flawless victory, gentlemen!

**Comment by sindresorhus** [comment]
Thanks for confirming :)

**Pull request merged**
